#ifndef BUILDINGBLOCKS_TT_INTERFACEMANAGER_RT_H
#define BUILDINGBLOCKS_TT_INTERFACEMANAGER_RT_H

#include "CKAll.h"

#define TERRATOOLS_GUID CKGUID(0x56495254, 0x4F4F4C53)

#endif // BUILDINGBLOCKS_TT_INTERFACEMANAGER_RT_H
