#ifndef BUILDINGBLOCKS_TT_TOOLBOX_RT_H
#define BUILDINGBLOCKS_TT_TOOLBOX_RT_H

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

#include "CKAll.h"

#define TERRATOOLS_GUID CKGUID(0x56495254, 0x4F4F4C53)

#endif // BUILDINGBLOCKS_TT_TOOLBOX_RT_H
