#ifndef PLAYER_CONFIG_H
#define PLAYER_CONFIG_H

#define PLAYER_VERSION_MAJOR 0
#define PLAYER_VERSION_MINOR 2
#define PLAYER_VERSION_PATCH 0
#define PLAYER_VERSION_TWEAK 0
#define PLAYER_VERSION "0.2.0.0"
#define PLAYER_DESCRIPTION "Ballance Decompilation"

#define PLAYER_DEFAULT_WIDTH 640
#define PLAYER_DEFAULT_HEIGHT 480
#define PLAYER_DEFAULT_BPP 32

#endif // PLAYER_CONFIG_H
