#define IDS_MAIN_WND_NAME               103
#define ID_ACCEL_HELP                   104
#define IDI_PLAYER                      107
#define IDR_ACCEL                       109
#define IDS_MAIN_WND_CLASS_NAME         109
#define IDS_RENDER_WND_CLASS_NAME       110
#define IDD_FULLSCREEN_SETUP            129
#define IDD_DIALOG                      141
#define IDC_LB_DRIVER                   1007
#define IDC_LB_SCREEN_MODE              1008
