# Remove only known plugin binaries left by a previous stage configuration.
# Keep user configuration, other plugins and assets. External install prefixes
# are never cleaned automatically.
if (NOT DEFINED BUILD_ROOT OR NOT DEFINED STAGE_ROOT OR
        NOT DEFINED CKRE_BUILD_BGFX_RASTERIZER OR NOT DEFINED CKRE_BUILD_SDL_GPU_RASTERIZER)
    message(FATAL_ERROR "Build/stage roots and both rasterizer options are required")
endif ()
file(REAL_PATH "${BUILD_ROOT}" _build_root)
file(REAL_PATH "${STAGE_ROOT}" _stage_root)
set(_disabled "")
if (NOT CKRE_BUILD_BGFX_RASTERIZER OR BALLANCE_BUILD_STATIC)
    list(APPEND _disabled CKBgfxRasterizer)
endif ()
if (NOT CKRE_BUILD_SDL_GPU_RASTERIZER OR BALLANCE_BUILD_STATIC)
    list(APPEND _disabled CKSdlGpuRasterizer)
endif ()
set(_remove "")
foreach (_name IN LISTS _disabled)
    foreach (_directory IN ITEMS Bin RenderEngines)
        foreach (_filename IN ITEMS "${_name}.dll" "${_name}.so" "lib${_name}.so"
                "${_name}.dylib" "lib${_name}.dylib")
            set(_path "${_stage_root}/${_directory}/${_filename}")
            if (EXISTS "${_path}" OR IS_SYMLINK "${_path}")
                file(REAL_PATH "${_path}" _resolved)
                cmake_path(IS_PREFIX _build_root "${_stage_root}" NORMALIZE _stage_in_build)
                cmake_path(IS_PREFIX _stage_root "${_resolved}" NORMALIZE _file_in_stage)
                if (NOT _stage_in_build OR _stage_root STREQUAL _build_root OR
                        NOT _file_in_stage OR IS_DIRECTORY "${_path}")
                    message(FATAL_ERROR "Cannot automatically remove stale rasterizer outside an isolated build stage: ${_path}")
                endif ()
                list(APPEND _remove "${_path}")
            endif ()
        endforeach ()
    endforeach ()
endforeach ()
# Validate the entire set before removing any files.
foreach (_path IN LISTS _remove)
    file(REMOVE "${_path}")
    if (EXISTS "${_path}" OR IS_SYMLINK "${_path}")
        message(FATAL_ERROR "Could not remove stale rasterizer (close the Player first): ${_path}")
    endif ()
    message(STATUS "[Stage] Removed disabled rasterizer: ${_path}")
endforeach ()
