# Component-owned data contracts, shared by stage and release-archive checks.
# Never execute files from an installed runtime or infer component options here.
file(GLOB _runtime_manifests "${STAGE_ROOT}/Bin/RuntimeManifests/*.json")
if (NOT _runtime_manifests)
    message(FATAL_ERROR "No component runtime manifests found")
endif ()
foreach (_manifest IN LISTS _runtime_manifests)
    file(READ "${_manifest}" _contract)
    foreach (_rule IN ITEMS required forbidden)
        string(JSON _count LENGTH "${_contract}" ${_rule})
        if (_count EQUAL 0)
            continue()
        endif ()
        math(EXPR _last "${_count} - 1")
        foreach (_index RANGE 0 ${_last})
            string(JSON _relative GET "${_contract}" ${_rule} ${_index})
            if (IS_ABSOLUTE "${_relative}" OR _relative MATCHES "(^|[/\\\\])\\.\\.([/\\\\]|$)")
                message(FATAL_ERROR "Invalid component runtime path: ${_relative}")
            endif ()
            set(_exists FALSE)
            if (EXISTS "${STAGE_ROOT}/${_relative}" OR IS_SYMLINK "${STAGE_ROOT}/${_relative}")
                set(_exists TRUE)
            endif ()
            if ((_rule STREQUAL "required" AND (NOT _exists OR IS_DIRECTORY "${STAGE_ROOT}/${_relative}")) OR
                    (_rule STREQUAL "forbidden" AND _exists))
                message(FATAL_ERROR "Component runtime contract violated (${_rule}): ${_relative}")
            endif ()
        endforeach ()
    endforeach ()
endforeach ()
