# .github/workflows/build-3.0.yml
name: Build with Virtools SDK 3.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release, Debug]
        
    uses: ./.github/workflows/build.yml
    with:
      branch: "${{ github.ref_name }}"
      sdk_version: "3.0"
      configuration: "${{ matrix.configuration }}"
